import { Device, GRN, SpareRequest, Engineer, PO, POItem, DropdownData, GRNType, SparePartInventory, IQCData, L3L4Data } from "./types";

export const mockEngineers: Engineer[] = [
  { id: "eng1", name: "Rahul Sharma", level: "L1" },
  { id: "eng2", name: "Priya Patel", level: "L2" },
  { id: "eng3", name: "Amit Singh", level: "L3" },
  { id: "eng4", name: "Neha Gupta", level: "L4" },
  { id: "monu", name: "Monu Kumar", level: "IQC" },
];

export const mockPOs: PO[] = [
  {
    id: "po1",
    poNumber: "PO-2026-001",
    poDate: new Date("2026-05-01"),
    vendorName: "TechSource Pvt Ltd",
    sgst: 9,
    cgst: 9,
    igst: 0,
    taxableAmount: 100000,
    taxAmount: 18000,
    invoiceValue: 118000,
    items: [
      {
        id: "poitem1",
        itemName: "Laptop Pro X1",
        subCategory: "Electronics",
        lotNumber: "LOT-001",
        customerName: "ABC Corp",
        purchaseOrder: "PO-2026-001",
        quantity: 5,
        make: "Dell",
        model: "XPS 13",
        unitPriceWithoutTax: 20000,
        unitPriceWithTax: 23600,
        itemValue: 118000,
        location: "Warehouse A",
        taxPercentage: 18,
        totalItemPrice: 118000,
        cpu: "Intel i7",
        generation: "13th Gen",
        ram: "16GB",
        hdd: "512GB SSD",
        ssdCapacity: "512GB",
        screenSize: "13.3\"",
      },
    ],
  },
];

export const mockGRNs: GRN[] = [
  {
    id: "grn1",
    grnNumber: "GRN-2026-001",
    grnType: "GRN",
    poNumber: "PO-2026-001",
    poDate: new Date("2026-05-01"),
    dateOfMaterialReceived: new Date("2026-05-10"),
    vendorNamePO: "TechSource Pvt Ltd",
    invoiceNumber: "INV-2026-001",
    invoiceDate: new Date("2026-05-09"),
    sgst: 9,
    cgst: 9,
    igst: 0,
    taxableAmount: 100000,
    taxAmount: 18000,
    invoiceValue: 118000,
    items: [
      {
        id: "grnitem1",
        itemName: "Laptop Pro X1",
        subCategory: "Electronics",
        lotNumber: "LOT-001",
        customerName: "ABC Corp",
        purchaseOrder: "PO-2026-001",
        quantityInInvoice: 5,
        physicalQuantity: 5,
        tagNumbers: ["TAG-001", "TAG-002", "TAG-003", "TAG-004", "TAG-005"],
        make: "Dell",
        model: "XPS 13",
        unitPriceWithoutTax: 20000,
        unitPriceWithTax: 23600,
        itemValue: 118000,
        location: "Warehouse A",
        taxPercentage: 18,
        totalItemPrice: 118000,
        cpu: "Intel i7",
        generation: "13th Gen",
        ram: "16GB",
        hdd: "512GB SSD",
      },
    ],
    totalPOQuantity: 5,
    totalInvoiceQuantity: 5,
    totalPhysicalQuantity: 5,
    variance: 0,
    taxableAmountInvoice: 100000,
    totalInvoiceValue: 118000,
    sgstInvoice: 9000,
    cgstInvoice: 9000,
    igstInvoice: 0,
    finalCheck: true,
    status: "Submitted",
    createdAt: new Date("2026-05-10"),
  },
];

export const mockDevices: Device[] = [
  {
    id: "dev1",
    inventoryAddedTime: new Date("2026-05-10"),
    userName: "Admin",
    poNumber: "PO-2026-001",
    grnNumber: "GRN-2026-001",
    grnDate: new Date("2026-05-10"),
    tagNumber: "TAG-001",
    serialNumber: "SN-001",
    make: "Dell",
    model: "XPS 13",
    cpu: "Intel i7",
    generation: "13th Gen",
    ram: "16GB",
    hdd: "512GB SSD",
    ssdCapacity: "512GB",
    screenSize: "13.3\"",
    productStage: "GRN",
    productStatus: "Available",
    masterCategory: "Electronics",
    subCategory: "Electronics",
    category: "Laptop",
    location: "Warehouse A",
    lotNumber: "LOT-001",
    totalInvoiceValue: 118000,
    invoiceNumber: "INV-2026-001",
    customerName: "ABC Corp",
    physicalQuantity: 5,
    vendorName: "TechSource Pvt Ltd",
    inventoryId: "INV-001",
    unitPriceWithTax: 23600,
    status: "Available",
    owner: "Inventory",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
    grnId: "grn1",
  },
  {
    id: "dev2",
    inventoryAddedTime: new Date("2026-05-10"),
    userName: "Admin",
    poNumber: "PO-2026-001",
    grnNumber: "GRN-2026-001",
    grnDate: new Date("2026-05-10"),
    tagNumber: "TAG-002",
    serialNumber: "SN-002",
    make: "Dell",
    model: "XPS 13",
    cpu: "Intel i7",
    generation: "13th Gen",
    ram: "16GB",
    hdd: "512GB SSD",
    ssdCapacity: "512GB",
    screenSize: "13.3\"",
    productStage: "GRN",
    productStatus: "Available",
    masterCategory: "Electronics",
    subCategory: "Electronics",
    category: "Laptop",
    location: "Warehouse A",
    lotNumber: "LOT-001",
    totalInvoiceValue: 118000,
    invoiceNumber: "INV-2026-001",
    customerName: "ABC Corp",
    physicalQuantity: 5,
    vendorName: "TechSource Pvt Ltd",
    inventoryId: "INV-002",
    unitPriceWithTax: 23600,
    status: "Available",
    owner: "Inventory",
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
    grnId: "grn1",
  },
  {
    id: "dev3",
    inventoryAddedTime: new Date("2026-05-15"),
    userName: "Admin",
    poNumber: "PO-2026-002",
    grnNumber: "GRN-2026-002",
    grnDate: new Date("2026-05-15"),
    tagNumber: "TAG-003",
    serialNumber: "SN-003",
    make: "HP",
    model: "ProBook 450",
    cpu: "Intel i5",
    generation: "12th Gen",
    ram: "8GB",
    hdd: "256GB SSD",
    ssdCapacity: "256GB",
    screenSize: "14\"",
    productStage: "Head Engineer",
    productStatus: "Assigned to Head Engineer",
    masterCategory: "Electronics",
    subCategory: "Electronics",
    category: "Laptop",
    location: "Warehouse A",
    lotNumber: "LOT-002",
    totalInvoiceValue: 82600,
    invoiceNumber: "INV-2026-002",
    customerName: "XYZ Ltd",
    physicalQuantity: 3,
    vendorName: "TechHub Solutions",
    inventoryId: "INV-003",
    unitPriceWithTax: 27533,
    status: "AssignedToHeadEngineer",
    owner: "HeadEngineer",
    createdAt: new Date("2026-05-15"),
    updatedAt: new Date("2026-05-15"),
    grnId: "grn2",
  },
  {
    id: "dev4",
    inventoryAddedTime: new Date("2026-05-15"),
    userName: "Admin",
    poNumber: "PO-2026-002",
    grnNumber: "GRN-2026-002",
    grnDate: new Date("2026-05-15"),
    tagNumber: "TAG-004",
    serialNumber: "SN-004",
    make: "Lenovo",
    model: "ThinkPad T14",
    cpu: "AMD Ryzen 7",
    generation: "5th Gen",
    ram: "32GB",
    hdd: "1TB SSD",
    ssdCapacity: "1TB",
    screenSize: "14\"",
    productStage: "Head Engineer",
    productStatus: "Assigned to Head Engineer",
    masterCategory: "Electronics",
    subCategory: "Electronics",
    category: "Laptop",
    location: "Warehouse A",
    lotNumber: "LOT-002",
    totalInvoiceValue: 147500,
    invoiceNumber: "INV-2026-003",
    customerName: "123 Industries",
    physicalQuantity: 2,
    vendorName: "TechHub Solutions",
    inventoryId: "INV-004",
    unitPriceWithTax: 73750,
    status: "AssignedToHeadEngineer",
    owner: "HeadEngineer",
    createdAt: new Date("2026-05-15"),
    updatedAt: new Date("2026-05-15"),
    grnId: "grn2",
  },
];

export const mockDropdownData: DropdownData = {
  grnTypes: ["GRN", "Spare Part GRN", "Consumable GRN"],
  poNumbers: ["PO-2026-001", "PO-2026-002"],
  customerNames: ["ABC Corp", "XYZ Ltd", "123 Industries", "Tech Solutions Inc"],
  makes: ["Dell", "HP", "Lenovo", "Apple"],
  models: ["XPS 13", "ProBook 450", "ThinkPad T14", "MacBook Pro"],
  locations: ["Warehouse A", "Warehouse B", "Warehouse C"],
  headEngineers: ["Monu Kumar", "Rahul Sharma"],
  ramStatuses: ["OK", "Faulty", "Needs Replacement"],
  spareParts: ["Battery", "Charger", "Cable", "RAM", "SSD", "HDD"],
  statuses: ["Pending", "In Progress", "Completed"],
  finalStatuses: ["Repairable", "Not Repairable", "Scrap"],
  problemsObserved: ["No Power", "Screen Issue", "Keyboard Not Working", "Overheating"],
  actionsTaken: ["Replaced Part", "Repaired", "Cleaned", "No Action"],
  customerInternal: ["Customer", "Internal"],
  scrapReasons: ["Beyond Repair", "Obsolete", "Damaged Beyond Repair"],
  hddSsdOptions: ["256GB SSD", "512GB SSD", "1TB SSD", "500GB HDD", "1TB HDD"],
  productStages: ["GRN", "Inventory", "Head Engineer", "IQC", "L1/L2", "L3/L4", "QC", "Closed"],
  productStatuses: ["Available", "Assigned", "In Repair", "Awaiting Spares", "QC Pending", "Closed"],
};

export const mockProducts: Product[] = [
  {
    id: "prod1",
    productOwner: "Oxypc Admin",
    productName: "Laptop Dell XPS 13",
    productType: "Electronics",
    productDescription: "High-performance laptop",
    hsnCode: "84713010",
    taxPreference: "Taxable",
    status: "Active",
    productNature: "Physical",
    masterCategory: "Electronics",
    category: "Laptop",
    subCategory: "Business Laptops",
    make: "Dell",
    model: "XPS 13",
    mrp: 100000,
    sellingPrice: 90000,
    costPrice: 80000,
    gstPercentage: 18,
    cgst: 9,
    sgst: 9,
    warehouse: "Warehouse A",
    openingStock: 50,
    reorderLevel: 10,
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-05-10"),
  },
];

export const mockSparePartInventory: SparePartInventory[] = [
  {
    id: "spinv1",
    inventoryAddedTime: new Date("2026-05-10"),
    poNumber: "PO-2026-001",
    grnDateAndTime: new Date("2026-05-10"),
    grnNumber: "GRN-2026-001",
    vendorName: "TechSource Pvt Ltd",
    invoiceNumber: "INV-2026-001",
    lotNumber: "LOT-001",
    productDescription: "16GB RAM Module",
    itemName: "RAM",
    crateTagNumber: "CRATE-RAM-001",
    make: "Corsair",
    model: "Vengeance LPX",
    sparePart: "RAM",
    invoiceQuantity: 10,
    physicalQuantity: 10,
    price: 5000,
    location: "Warehouse A",
    masterCategory: "Spare Parts",
    category: "RAM",
    subCategory: "Electronics",
    vehicleNumber: "DL-01-AB-1234",
    totalInvoiceValue: 50000,
  },
];

export const mockSpareRequests: SpareRequest[] = [
  {
    id: "spare1",
    deviceId: "dev1",
    partName: "Battery",
    quantity: 1,
    requestedBy: "eng2",
    requestedByLevel: "L2",
    status: "PendingApproval",
    createdAt: new Date("2026-05-13"),
  },
];
