/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreManagerRouteImport } from './routes/store-manager'
import { Route as SparePartsRouteImport } from './routes/spare-parts'
import { Route as SpareInventoryRouteImport } from './routes/spare-inventory'
import { Route as QcRouteImport } from './routes/qc'
import { Route as ProductMasterRouteImport } from './routes/product-master'
import { Route as L3L4RouteImport } from './routes/l3-l4'
import { Route as L1L2RouteImport } from './routes/l1-l2'
import { Route as IqcRouteImport } from './routes/iqc'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HeadEngineerRouteImport } from './routes/head-engineer'
import { Route as GrnReportRouteImport } from './routes/grn-report'
import { Route as GrnRouteImport } from './routes/grn'
import { Route as AssignByScanRouteImport } from './routes/assign-by-scan'
import { Route as ModuleRouteImport } from './routes/$module'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsCreateRouteImport } from './routes/products.create'

const StoreManagerRoute = StoreManagerRouteImport.update({
  id: '/store-manager',
  path: '/store-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const SparePartsRoute = SparePartsRouteImport.update({
  id: '/spare-parts',
  path: '/spare-parts',
  getParentRoute: () => rootRouteImport,
} as any)
const SpareInventoryRoute = SpareInventoryRouteImport.update({
  id: '/spare-inventory',
  path: '/spare-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductMasterRoute = ProductMasterRouteImport.update({
  id: '/product-master',
  path: '/product-master',
  getParentRoute: () => rootRouteImport,
} as any)
const L3L4Route = L3L4RouteImport.update({
  id: '/l3-l4',
  path: '/l3-l4',
  getParentRoute: () => rootRouteImport,
} as any)
const L1L2Route = L1L2RouteImport.update({
  id: '/l1-l2',
  path: '/l1-l2',
  getParentRoute: () => rootRouteImport,
} as any)
const IqcRoute = IqcRouteImport.update({
  id: '/iqc',
  path: '/iqc',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadEngineerRoute = HeadEngineerRouteImport.update({
  id: '/head-engineer',
  path: '/head-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnReportRoute = GrnReportRouteImport.update({
  id: '/grn-report',
  path: '/grn-report',
  getParentRoute: () => rootRouteImport,
} as any)
const GrnRoute = GrnRouteImport.update({
  id: '/grn',
  path: '/grn',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignByScanRoute = AssignByScanRouteImport.update({
  id: '/assign-by-scan',
  path: '/assign-by-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/$module',
  path: '/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCreateRoute = ProductsCreateRouteImport.update({
  id: '/products/create',
  path: '/products/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/assign-by-scan': typeof AssignByScanRoute
  '/grn': typeof GrnRoute
  '/grn-report': typeof GrnReportRoute
  '/head-engineer': typeof HeadEngineerRoute
  '/inventory': typeof InventoryRoute
  '/iqc': typeof IqcRoute
  '/l1-l2': typeof L1L2Route
  '/l3-l4': typeof L3L4Route
  '/product-master': typeof ProductMasterRoute
  '/qc': typeof QcRoute
  '/spare-inventory': typeof SpareInventoryRoute
  '/spare-parts': typeof SparePartsRoute
  '/store-manager': typeof StoreManagerRoute
  '/products/create': typeof ProductsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/assign-by-scan': typeof AssignByScanRoute
  '/grn': typeof GrnRoute
  '/grn-report': typeof GrnReportRoute
  '/head-engineer': typeof HeadEngineerRoute
  '/inventory': typeof InventoryRoute
  '/iqc': typeof IqcRoute
  '/l1-l2': typeof L1L2Route
  '/l3-l4': typeof L3L4Route
  '/product-master': typeof ProductMasterRoute
  '/qc': typeof QcRoute
  '/spare-inventory': typeof SpareInventoryRoute
  '/spare-parts': typeof SparePartsRoute
  '/store-manager': typeof StoreManagerRoute
  '/products/create': typeof ProductsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$module': typeof ModuleRoute
  '/assign-by-scan': typeof AssignByScanRoute
  '/grn': typeof GrnRoute
  '/grn-report': typeof GrnReportRoute
  '/head-engineer': typeof HeadEngineerRoute
  '/inventory': typeof InventoryRoute
  '/iqc': typeof IqcRoute
  '/l1-l2': typeof L1L2Route
  '/l3-l4': typeof L3L4Route
  '/product-master': typeof ProductMasterRoute
  '/qc': typeof QcRoute
  '/spare-inventory': typeof SpareInventoryRoute
  '/spare-parts': typeof SparePartsRoute
  '/store-manager': typeof StoreManagerRoute
  '/products/create': typeof ProductsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$module'
    | '/assign-by-scan'
    | '/grn'
    | '/grn-report'
    | '/head-engineer'
    | '/inventory'
    | '/iqc'
    | '/l1-l2'
    | '/l3-l4'
    | '/product-master'
    | '/qc'
    | '/spare-inventory'
    | '/spare-parts'
    | '/store-manager'
    | '/products/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$module'
    | '/assign-by-scan'
    | '/grn'
    | '/grn-report'
    | '/head-engineer'
    | '/inventory'
    | '/iqc'
    | '/l1-l2'
    | '/l3-l4'
    | '/product-master'
    | '/qc'
    | '/spare-inventory'
    | '/spare-parts'
    | '/store-manager'
    | '/products/create'
  id:
    | '__root__'
    | '/'
    | '/$module'
    | '/assign-by-scan'
    | '/grn'
    | '/grn-report'
    | '/head-engineer'
    | '/inventory'
    | '/iqc'
    | '/l1-l2'
    | '/l3-l4'
    | '/product-master'
    | '/qc'
    | '/spare-inventory'
    | '/spare-parts'
    | '/store-manager'
    | '/products/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuleRoute: typeof ModuleRoute
  AssignByScanRoute: typeof AssignByScanRoute
  GrnRoute: typeof GrnRoute
  GrnReportRoute: typeof GrnReportRoute
  HeadEngineerRoute: typeof HeadEngineerRoute
  InventoryRoute: typeof InventoryRoute
  IqcRoute: typeof IqcRoute
  L1L2Route: typeof L1L2Route
  L3L4Route: typeof L3L4Route
  ProductMasterRoute: typeof ProductMasterRoute
  QcRoute: typeof QcRoute
  SpareInventoryRoute: typeof SpareInventoryRoute
  SparePartsRoute: typeof SparePartsRoute
  StoreManagerRoute: typeof StoreManagerRoute
  ProductsCreateRoute: typeof ProductsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-manager': {
      id: '/store-manager'
      path: '/store-manager'
      fullPath: '/store-manager'
      preLoaderRoute: typeof StoreManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-parts': {
      id: '/spare-parts'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof SparePartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spare-inventory': {
      id: '/spare-inventory'
      path: '/spare-inventory'
      fullPath: '/spare-inventory'
      preLoaderRoute: typeof SpareInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-master': {
      id: '/product-master'
      path: '/product-master'
      fullPath: '/product-master'
      preLoaderRoute: typeof ProductMasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l3-l4': {
      id: '/l3-l4'
      path: '/l3-l4'
      fullPath: '/l3-l4'
      preLoaderRoute: typeof L3L4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/l1-l2': {
      id: '/l1-l2'
      path: '/l1-l2'
      fullPath: '/l1-l2'
      preLoaderRoute: typeof L1L2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqc': {
      id: '/iqc'
      path: '/iqc'
      fullPath: '/iqc'
      preLoaderRoute: typeof IqcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/head-engineer': {
      id: '/head-engineer'
      path: '/head-engineer'
      fullPath: '/head-engineer'
      preLoaderRoute: typeof HeadEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn-report': {
      id: '/grn-report'
      path: '/grn-report'
      fullPath: '/grn-report'
      preLoaderRoute: typeof GrnReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grn': {
      id: '/grn'
      path: '/grn'
      fullPath: '/grn'
      preLoaderRoute: typeof GrnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assign-by-scan': {
      id: '/assign-by-scan'
      path: '/assign-by-scan'
      fullPath: '/assign-by-scan'
      preLoaderRoute: typeof AssignByScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$module': {
      id: '/$module'
      path: '/$module'
      fullPath: '/$module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/create': {
      id: '/products/create'
      path: '/products/create'
      fullPath: '/products/create'
      preLoaderRoute: typeof ProductsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuleRoute: ModuleRoute,
  AssignByScanRoute: AssignByScanRoute,
  GrnRoute: GrnRoute,
  GrnReportRoute: GrnReportRoute,
  HeadEngineerRoute: HeadEngineerRoute,
  InventoryRoute: InventoryRoute,
  IqcRoute: IqcRoute,
  L1L2Route: L1L2Route,
  L3L4Route: L3L4Route,
  ProductMasterRoute: ProductMasterRoute,
  QcRoute: QcRoute,
  SpareInventoryRoute: SpareInventoryRoute,
  SparePartsRoute: SparePartsRoute,
  StoreManagerRoute: StoreManagerRoute,
  ProductsCreateRoute: ProductsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
